// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/search-products.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("Supabase publishable key is required");
}

// src/lib/mcp/tools/search-products.ts
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search real, in-stock fashion products from Shopify stores that ship to the US.",
  inputSchema: {
    query: z.string().trim().min(2).max(300).describe("What to shop for, e.g. 'cream linen midi dress'."),
    limit: z.number().int().min(1).max(20).optional().describe("Max products to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, limit }, ctx) => {
    const key = supabasePublishableKey();
    const res = await fetch(`${supabaseProjectUrl()}/functions/v1/shopify-catalog`, {
      method: "POST",
      headers: { "Content-Type": "application/json", apikey: key, Authorization: `Bearer ${key}` },
      body: JSON.stringify({ query }),
      signal: ctx.signal
    });
    const body = await res.json().catch(() => null);
    if (!res.ok || !Array.isArray(body?.products)) {
      throw new ToolError(body?.error ?? `Product search failed (${res.status}).`);
    }
    const products = body.products.filter((p) => p.title && p.productUrl && p.price).slice(0, limit ?? 10).map((p) => ({
      title: p.title ?? "",
      price: p.price ? (p.price.amount / 100).toFixed(2) : "",
      currency: p.price?.currency ?? "",
      merchant: p.merchantName ?? "",
      url: p.productUrl ?? "",
      imageUrl: p.imageUrl ?? ""
    }));
    const text = products.length ? products.map((p) => `- ${p.title} \u2014 ${p.price} ${p.currency} at ${p.merchant}: ${p.url}`).join("\n") : "No products found.";
    return { content: [{ type: "text", text }], structuredContent: { products } };
  }
});

// src/lib/mcp/tools/list-aesthetics.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.4";

// supabase/functions/_shared/aesthetics.ts
var AESTHETICS = [
  { name: "Brownstone Minimal", definition: "warm, quiet tailoring in a few good neutrals (camel coats, black knits, wide-leg denim, gold)" },
  { name: "Downtown Uniform", definition: "all black with edge (leather jackets, washed black denim, lug boots, silver)" },
  { name: "Off-Duty Muse", definition: "easy denim basics (white tanks, baggy jeans, chunky sneakers, ball caps)" },
  { name: "Gallery Hours", definition: "one bold color against quiet neutrals, sculptural shapes" },
  { name: "East Village Romantic", definition: "dark, moody romance (lace, velvet, dark florals, sheer layers)" },
  { name: "Upper West Prep", definition: "academic and put-together (plaid, cable knits, blazers, loafers)" },
  { name: "Midtown Power", definition: "sharp suiting with strong shoulders and '80s confidence" },
  { name: "Broadway Maximalist", definition: "prints, color clash and statement accessories" },
  { name: "Tribeca Archive", definition: "vintage designer pieces worn as everyday clothes" },
  { name: "Prospect Park Sport", definition: "athletic pieces styled for the street (track pants, retro sneakers)" },
  { name: "Nolita Soft", definition: "sweet and feminine (pink, bows, satin, ballet flats)" },
  { name: "Bushwick Experimental", definition: "avant-garde, asymmetric, deconstructed" }
];
var AESTHETIC_NAMES = AESTHETICS.map((a) => a.name);

// src/lib/mcp/tools/list-aesthetics.ts
var list_aesthetics_default = defineTool2({
  name: "list_aesthetics",
  title: "List style aesthetics",
  description: "List the 12 MatchMyStyle New York style aesthetics with short definitions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const aesthetics = AESTHETICS.map((a) => ({ name: a.name, definition: a.definition }));
    return {
      content: [{ type: "text", text: aesthetics.map((a) => `${a.name}: ${a.definition}`).join("\n") }],
      structuredContent: { aesthetics }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "style-matcher-pro",
  title: "Style Matcher Pro",
  version: "0.1.0",
  instructions: "MatchMyStyle fashion tools. Use `list_aesthetics` to see the 12 style aesthetics, and `search_products` to find real in-stock products from Shopify stores (prices and links are verified catalog data).",
  tools: [search_products_default, list_aesthetics_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
